# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digaz < Formula
  desc "Look up region and other information for any Azure IP address"
  homepage "https://github.com/sampointer/digaz"
  version "0.3.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sampointer/digaz/releases/download/v0.3.2/digaz_0.3.2_Darwin_x86_64.tar.gz"
    sha256 "af046692b3639d5e95a1d7ce42a08603a344d3530a766ff169c231a458f2fb91"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sampointer/digaz/releases/download/v0.3.2/digaz_0.3.2_Linux_x86_64.tar.gz"
    sha256 "18a41a2cdab31aad3e78e17250242769c521c75400fa713df3f2bbaef70641aa"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sampointer/digaz/releases/download/v0.3.2/digaz_0.3.2_Linux_arm64.tar.gz"
    sha256 "bab19623ff1fb493fe96bc9b6e183fef864f20804e3277a5b57107396c2ea608"
  end

  def install
    bin.install "digaz"
  end
end
