# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digaz < Formula
  desc "Look up region and other information for any Azure IP address"
  homepage "https://github.com/sampointer/digaz"
  version "0.3.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sampointer/digaz/releases/download/v0.3.3/digaz_0.3.3_Darwin_x86_64.tar.gz"
      sha256 "2d42bf1eefeb495030ea7ee365702ea195de39e6f9940105d800e4d1c5a38947"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sampointer/digaz/releases/download/v0.3.3/digaz_0.3.3_Linux_x86_64.tar.gz"
      sha256 "b3d32d3a18dd56e1635bc9646fb50fe2f2e85cbf1c52743ec28f260ad3e0a268"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sampointer/digaz/releases/download/v0.3.3/digaz_0.3.3_Linux_arm64.tar.gz"
      sha256 "09c148754e2e2045ef9e96c23801acb32f0af27244d8ad85f410365f09395904"
    end
  end

  def install
    bin.install "digaz"
  end
end
